"""Constants for the Kuehlgeraet Cockpit integration."""

from __future__ import annotations

DOMAIN = "kuehlgeraet_cockpit"

PLATFORMS = ["sensor", "binary_sensor", "switch", "number"]

CONF_TARGET_ENTITY = "target_entity"
CONF_TURN_ON_SERVICE = "turn_on_service"
CONF_TURN_OFF_SERVICE = "turn_off_service"
CONF_TURN_ON_ACTION_ENTITIES = "turn_on_action_entities"
CONF_TURN_OFF_ACTION_ENTITIES = "turn_off_action_entities"
CONF_TEMPERATURE_ENTITY = "temperature_entity"
CONF_POWER_ENTITY = "power_entity"
CONF_PRICE_ENTITY = "price_entity"
CONF_PRICE_MIN_ENTITY = "price_min_entity"
CONF_PRICE_MAX_ENTITY = "price_max_entity"
CONF_CHEAP_ENTITY = "cheap_entity"
CONF_AUTO_APPLY = "auto_apply"
CONF_FAILSAFE_ON = "failsafe_on"
CONF_EVALUATION_INTERVAL = "evaluation_interval"
CONF_COMPRESSOR_RUNNING_WATTS = "compressor_running_watts"
CONF_MIN_ON_SECONDS = "min_on_seconds"
CONF_MIN_OFF_SECONDS = "min_off_seconds"
CONF_CHEAP_ON_TEMP = "cheap_on_temp"
CONF_CHEAP_OFF_TEMP = "cheap_off_temp"
CONF_EXPENSIVE_ON_TEMP = "expensive_on_temp"
CONF_EXPENSIVE_OFF_TEMP = "expensive_off_temp"

CONF_CONFIG_ENTRY_ID = "config_entry_id"
CONF_ENABLED = "enabled"
CONF_SETTING = "setting"
CONF_VALUE = "value"
CONF_APPLY = "apply"

DEFAULT_TARGET_ENTITY = ""
DEFAULT_TARGET_ENTITIES: list[str] = []
DEFAULT_TURN_ON_SERVICE = "homeassistant.turn_on"
DEFAULT_TURN_OFF_SERVICE = "homeassistant.turn_off"
DEFAULT_TURN_ON_ACTION_ENTITIES: list[str] = []
DEFAULT_TURN_OFF_ACTION_ENTITIES: list[str] = []
DEFAULT_TEMPERATURE_ENTITY = ""
DEFAULT_POWER_ENTITY = ""
DEFAULT_PRICE_ENTITY = ""
DEFAULT_PRICE_MIN_ENTITY = ""
DEFAULT_PRICE_MAX_ENTITY = ""
DEFAULT_CHEAP_ENTITY = ""
DEFAULT_AUTO_APPLY = True
DEFAULT_FAILSAFE_ON = True
DEFAULT_EVALUATION_INTERVAL = 300
DEFAULT_COMPRESSOR_RUNNING_WATTS = 15.0
DEFAULT_MIN_ON_SECONDS = 300
DEFAULT_MIN_OFF_SECONDS = 300
DEFAULT_CHEAP_ON_TEMP = 4.0
DEFAULT_CHEAP_OFF_TEMP = 2.0
DEFAULT_EXPENSIVE_ON_TEMP = 6.0
DEFAULT_EXPENSIVE_OFF_TEMP = 4.0
DATA_RUNTIME = "runtime"
DATA_SERVICES_REGISTERED = "services_registered"
DATA_PANEL_REGISTERED = "panel_registered"

SERVICE_EVALUATE_NOW = "evaluate_now"
SERVICE_SET_ENABLED = "set_enabled"
SERVICE_SET_SIMULATION = "set_simulation"
SERVICE_SET_SETTING = "set_setting"

STORAGE_VERSION = 2
STORAGE_KEY = f"{DOMAIN}_runtime"

STATUS_SENSOR_UNIQUE_ID = f"{DOMAIN}_status"
STATUS_SENSOR_NAME = "Kuehlgeraet Cockpit Status"
ENABLED_SWITCH_UNIQUE_ID = f"{DOMAIN}_enabled"
SIMULATION_SWITCH_UNIQUE_ID = f"{DOMAIN}_simulation"

PANEL_URL_PATH = "kuehlgeraet-cockpit"
PANEL_STATIC_URL = f"/{DOMAIN}/frontend"
PANEL_FILENAME = "kuehlgeraet-cockpit-panel.js"
PANEL_ELEMENT = "kuehlgeraet-cockpit-panel"

RUNTIME_SETTING_KEYS = {
    CONF_COMPRESSOR_RUNNING_WATTS,
    CONF_MIN_ON_SECONDS,
    CONF_MIN_OFF_SECONDS,
    CONF_CHEAP_ON_TEMP,
    CONF_CHEAP_OFF_TEMP,
    CONF_EXPENSIVE_ON_TEMP,
    CONF_EXPENSIVE_OFF_TEMP,
}

NUMERIC_SETTING_DEFAULTS = {
    CONF_COMPRESSOR_RUNNING_WATTS: DEFAULT_COMPRESSOR_RUNNING_WATTS,
    CONF_MIN_ON_SECONDS: DEFAULT_MIN_ON_SECONDS,
    CONF_MIN_OFF_SECONDS: DEFAULT_MIN_OFF_SECONDS,
    CONF_CHEAP_ON_TEMP: DEFAULT_CHEAP_ON_TEMP,
    CONF_CHEAP_OFF_TEMP: DEFAULT_CHEAP_OFF_TEMP,
    CONF_EXPENSIVE_ON_TEMP: DEFAULT_EXPENSIVE_ON_TEMP,
    CONF_EXPENSIVE_OFF_TEMP: DEFAULT_EXPENSIVE_OFF_TEMP,
}
